#footprint: [[-0.10, -0.10], [-0.10, 0.10], [0.10, 0.10], [0.10, -0.10]]
robot_radius: 0.11
footprint_padding: 0.01
inflation_radius: 0.05

robot_base_frame: base_footprint
update_frequency: 4
publish_frequency: 3
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 8.0

#layer definitions



static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser_layer:
    observation_sources: base_sensor
    base_sensor: {sensor_frame: laser, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

range_sensor_layer:
    ns: /ultra
    clear_threshold: 0.1
    mark_threshold: 0.6
    clear_on_max_reading: true
    topics: ["/left_scan", "/middle_scan", "/right_scan"]

inflation_g:
    inflation_radius: 2
    
inflation_l:
    inflation_radius: 2