global_frame: map
rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser_layer,           type: "costmap_2d::ObstacleLayer"}
#  - {name: range_sensor_layer,                 type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_g,               type: "costmap_2d::InflationLayer"}
